apiVersion: apps/v1
kind: Deployment
metadata:
   name: air_transoprt_service
spec:
   strategy:
    type: Recreate
   selector:
    matchLabels:
      app: air_transoprt_service
   template:
    metadata:
      labels:
        app: air_transoprt_service
    spec:
      containers:
      - name: air_transoprt_service
        image: skannte/air_transoprt_service:latest
        imagePullPolicy: Always
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        - name: AirTransportServicePath
          value: /usr/data
        ports:
        - containerPort: 5002
        volumeMounts:
        - name: sqlite-volume
          mountPath: /usr/data
      volumes:
      - name: sqlite-volume
        persistentVolumeClaim:
          claimName: sqlite-pvc

  